name: create-issues

on: workflow_dispatch

env:
  TEMPLATE_REPO: the-collab-lab/smart-shopping-list
  # For using the GitHub CLI:
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  get-issues-from-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Get issues JSON from template repo
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$TEMPLATE_REPO/issues > issues.json
          echo "**********"
          cat issues.json
      - name: Sort issue objects in JSON file by GitHub issue number
        # Note: This assumes that we'll always keep the GitHub issues in the template repo
        #  in order. (i.e. The first issue Collabies tackle will have the lowest issue
        #  number, the second issue Collabies tackle will have the next lowest number, and so on.)
        run: |
          jq 'sort_by(.number)' issues.json > issues.json
          echo "**********"
          cat issues.json
      - name: Create new GitHub issues in the current repo
        run: |
          NUM_ISSUES = $(jq '. | length' issues.json)

          for (( i=0; i<$NUM_ISSUES; i++ ))
          do
            TITLE = $(jq '.[$i].title' issues.json)
            BODY = $(jq '.[$i].body' issues.json)
            echo "**********"
            echo "TITLE: ${TITLE}"
            echo "BODY: ${BODY}"
          done
