name: create-issues

on: workflow_dispatch

env:
  # For using the GitHub CLI:
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  get-issues-from-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Get issues JSON from template repo
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/the-collab-lab/smart-shopping-list/issues > issues.json
          echo "**********"
          cat issues.json
      - name: Check if jq works in GitHub Action
        run: jq . issues.json
